Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -24,6 +24,6 @@ jobs:
           version=$(jq -rn '""')
           if [[ -z "$version" ]]; then
             printf 'test\n' >&2
-            printf '::error::invalid "packageManager" in package.json\naaaa\n'
-            exit 1;
+            printf '::error::invalid "packageManager" in package.json%0Aaaaa\n'
+            exit 1 &> /dev/null;
           fi
