Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -23,7 +23,7 @@ jobs:
           echo "$(cksum -a sha256 --untagged ${file})"
           version=$(jq -rn '""')
           if [[ -z "$version" ]]; then
-            echo '::error::invalid "packageManager" in package.json\naaaa'
+            echo "::error::invalid \"packageManager\" in package.json\naaaa"
             echo 'bbbbbbbb'
-            exit;
+            exit 1;
           fi
